ContactController Test Unit Created
dsc-upt/gdsc-backend pull request #14
Opened 2021-04-20 18:16 UTC by mrsaibaandreas

2021-04-20 21:05 UTC, danpercic86 requested changes

2021-04-20 21:05 UTC, danpercic86 commented on gdsc-web-backend.tests/ContactControllerTests.cs
> +            //verified if the values are not null
That's self explanatory, no need for comment

2021-04-20 21:05 UTC, danpercic86 commented on gdsc-web-backend.tests/ContactControllerTests.cs
> +            Assert.Equal(StatusCodes.Status201Created, added1.StatusCode);
Also here verify if the returned object is equal to the one that was sent to Post method, not only status code, for both examples

2021-04-20 21:05 UTC, danpercic86 commented on gdsc-web-backend/.dockerignore
> +bin/
.dockerignore  file has nothing to do with controller testing

2021-04-20 21:05 UTC, danpercic86 commented on gdsc-web-backend/Controllers/ContactController.cs
> +            return Created("api/Contact/" + entity!.Id, entity);
Here we should return only Ok(entity), since contact has not Get method to use for returned url

2021-04-20 21:05 UTC, danpercic86 commented on gdsc-web-backend/Dockerfile
> +WORKDIR /app
These docker files have nothing to do with the contact controller testing

2021-04-21 09:56 UTC, mrsaibaandreas commented
Made all the requested changes to the code.

2021-04-21 11:38 UTC, danpercic86 commented
Now it looks better, gj!

2021-04-21 11:38 UTC, merged